services:
  pikmiverse-web:
    platform: linux/arm64
    build:
      context: ./pikmiverse-web
    image: pikmiverse-web
    container_name: pikmiverse-web
    ports:
      - "80:80"
    tty: true
    networks:
      - pikmiverse-network

  pikmiverse-api:
    platform: linux/arm64
    build:
      context: ./pikmiverse-api
    image: pikmiverse-api
    container_name: pikmiverse-api
    ports:
      - "8000:8000"
    networks:
      - pikmiverse-network

  # pikmiverse-redis:
  #   platform: linux/arm64
  #   build:
  #     context: ./pikmiverse-redis
  #   image: pikmiverse-redis
  #   container_name: pikmiverse-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - pikmiverse-network

  # pikmiverse-mqtt:
  #   platform: linux/arm64
  #   build:
  #     context: ./pikmiverse-mqtt
  #   image: pikmiverse-mqtt
  #   container_name: pikmiverse-mqtt
  #   ports:
  #     - "1883:1883"
  #     - "8883:8883"
  #   networks:
  #     - pikmiverse-network

  # pikmiverse-db:
  #   platform: linux/arm64
  #   image: postgres:15-alpine
  #   container_name: pikmiverse-db
  #   env_file:
  #     - ./pikmiverse-api/.env.db
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - pikmiverse-network

networks:
  pikmiverse-network:
    driver: bridge
